### ISSUE TITLE
MatrixError: [500] Unable to query user profile, no profile found

### ISSUE THREAD

**Issue by ghost** [geekgonecrazy/rocketchat-matrix-federation-example#1]
@geekgonecrazy I'm investing IM federation with Rocket.chat and Matrix; I followed your tutorial and had some success creating a federated channel (invitation pops up in element after I create it in Rocket.chat), but when I try to send a message in element I get a 'Failed to Join' alert message with the above error. Have you run into this / any ideas?

**Comment by geekgonecrazy** [comment]
Glad you had some success.  I'd suggest opening an issue on the Rocket.chat repo.  My example might not be 100% up to date any more.

The team has changed a lot in last few versions.  Going to close the issue here

**Comment by ghost** [comment]
Thanks Aaron - as you may have seen on open RC I managed to figure out the issue (started working when I opened up the user registration on the Matrix server rather than using the secret to generate one). I'm thinking of trying to update the image versions in the docker compose - do you think that might be useful for this repo?

**Comment by geekgonecrazy** [comment]
Definitely feel free to :pray:  I unfortunately haven't had a chance to try with newer versions
